# Default values for odoo.
# This is a YAML-formatted file.

# -- overrides the name of the chart, ignoring what is used at deployment
nameOverride: ""

# -- imagePullSecrets will be propagated to all containers, if set
imagePullSecrets: []

# --- if true, a "rollme" annotation will be written to deployment manifests, that always changes every upgrade. If you do not tag your images this will be required to swap the container image
rollme: false

image:
  # -- container image
  repository: glodouk/CHANGEME
  # -- container tag
  tag: ""
  # -- container pullPolicy
  pullPolicy: IfNotPresent

config:
  # -- sets odoo configuration proxy_mode
  proxyMode: "true"
  # -- sets odoo configuration without_demo
  withoutDemo: "true"
  # -- sets odoo configuration list_db
  listDB: "true"
  # -- sets odoo configuration db_filter
  dbFilter: ".*"
  # -- sets odoo configuration admin_password
  adminPassword: ""

  postgresql:
    # -- sets both odoo configuration db_host and environment variable PGHOST
    host: ""
    # -- sets both odoo configuration db_username and environment variable PGUSER
    user: ""
    # -- sets both odoo configuration db_password and environment variable PGPASSWORD
    password: ""
    # -- sets both odoo configuration db_port and environment variable PGPORT
    port: 5432
    # -- sets both odoo configuration PGDATABASE, if you are setting this, you
    # probably waant to also set config.dbFilter
    database: ""

  smtp:
    # -- sets odoo configuration smtp_server
    host: "false"
    # -- sets odoo configuration smtp_port
    port: "false"
    # -- sets odoo configuration smtp_user
    user: "false"
    # -- sets odoo configuration smtp_password
    password: "false"
    # -- sets odoo configuration smtp_ssl
    ssl: "false"

persistence:
  # -- enable /var/lib/odoo persistence, without persistence it will be temporary - and that's a bad thing!
  enabled: true
  name: "storage"
  storageClassName: "nfs-client"
  existingClaim: ""
  annotations: {}
  # -- when running deployment with replicas > 1 ReadWriteMany is a requirement, if you are in an environment without ReadWriteMany available then you will need to find an alternative solution i.e. https://github.com/camptocamp/odoo-cloud-platform/tree/14.0/base_attachment_object_storage
  accessMode: ReadWriteMany
  size: 100Gi

web:
  # -- enable Odoo web worker
  enabled: true
  name: "web"

  # -- optional extra configuration options that Doodba does not allow to be set
  # -- through environment variables
  config: |
    [options]
    limit_memory_soft = 3758096384
    limit_memory_hard = 4294967296
    limit_time_cpu = 360
    limit_time_real = 360
    limit_time_real_cron = 360
    max_cron_threads = 1
    workers = 5
    longpolling_port = 8072

  replicaCount: 1
  service:
    type: ClusterIP

  # -- kubernetes Deployment strategy, note: queue is always set to Recreate,
  strategy:
    type: RollingUpdate

  dns:
    # -- enables external-dns CRD (DNSEndpoint) creation
    enabled: false
    # -- must be DNSEndpoint compatible
    # As of time of writing only A, CNAME, TXT and SRV records are supported
    # See: https://github.com/ytsarev/external-dns/blob/master/endpoint/endpoint.go#L27-L36
    # ```yaml
    # - dnsName: "something.domain"
    #   recordTTL: 60
    #   recordType: A
    #   targets:
    #     - xx.xx.xx.xx
    # ```
    endPoints: []

  certificate:
    # -- enables cert-manager Certificate CRD creation
    enabled: false
    secretName: "odoo-web"
    dnsNames: []
    issuerRef:
      name: letsencrypt
      kind: ClusterIssuer

  ingress:
    # -- enable Ingress or Traefik IngressRoute creation
    enabled: true

    # -- IngressRoute or Ingress, when set to IngressRoute will render an Traefik IngressRoute
    type: "IngressRoute"

    # -- extra annotations passed to Ingress or IngressRoute, if type is IngressRoute
    annotations: {}

    # -- if type is IngressRoute then the IngressRoute entryPoint, if type is Ingress then it will automatically set the entrypoint annotation
    entryPoints:
      - websecure

    # -- if type is IngressRoute then a string of IngressRoute compatible matches
    match: Host(`chart-example.local`)

    # -- if type is Ingress then a list of host names to match, if not using certificate CRD then also used for tls host names
    hosts:
      - chart-example.local

    # -- if type is IngressRoute then Traefik Middlewares, if type is Ingress then it will automatically set Ingress annotations
    middlewares: []

    # -- Automatically create a Traefik compress middleware
    compress: false

    # -- tls options
    tls:
      secretName: ""
      certResolver: "letsencrypt"

    # -- "longpolling" path. Under 16.0 this should be changed for /websocket
    geventPath: "/longpolling/"

  livenessProbe:
    # -- enable livenessProbe
    enabled: false
    # -- livenessProbe configuration, note that /web/health did not until mid-way through the 15.0 release, therefore we suggest tcpSocket
    values:
      tcpSocket:
        port: http
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 60

  readinessProbe:
    # -- enable readinessProbe
    enabled: false
    # -- readinessProbe configuration, note that /web/health did not until mid-way through the 15.0 release, therefore we suggest tcpSocket
    values:
      tcpSocket:
        port: http
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 60

  # -- optional extra volumes
  extraVolumes: []

  # -- optional extra volume mounts
  extraVolumeMounts: []

  # -- optional extra environment variables
  extraEnv: []
  # - name: DO_STUFF
  #   value: true

  # -- optional extra containers
  extraContainers: []

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

longpolling:
  # -- enable a separate longpolling instance, both web and longpolling must be enabled
  enabled: false
  name: "longpolling"

  # -- optional extra configuration options that Doodba does not allow to be set
  # -- through environment variables
  config: |
    [options]
    limit_memory_soft = 3758096384
    limit_memory_hard = 4294967296
    limit_time_cpu = 360
    limit_time_real = 360
    limit_time_real_cron = 360
    max_cron_threads = 0
    workers = 5
    longpolling_port = 8072

  replicaCount: 1
  service:
    type: ClusterIP

  # -- kubernetes Deployment strategy, note: queue is always set to Recreate,
  strategy:
    type: RollingUpdate

  # -- optional extra volumes
  extraVolumes: []

  # -- optional extra volume mounts
  extraVolumeMounts: []

  # -- optional extra containers
  extraContainers: []

  # -- optional extra environment variables
  extraEnv: []
  # - name: DO_STUFF
  #   value: true

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1

  livenessProbe:
    # -- enable livenessProbe
    enabled: false
    # -- livenessProbe configuration, note that /web/health did not until mid-way through the 15.0 release, therefore we suggest tcpSocket
    values:
      tcpSocket:
        port: longpolling
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 60

  readinessProbe:
    # -- enable readinessProbe
    enabled: false
    # -- readinessProbe configuration, note that /web/health did not until mid-way through the 15.0 release, therefore we suggest tcpSocket
    values:
      tcpSocket:
        port: longpolling
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 60

queue:
  # -- enable a second deployment, specifically running oca/queue_job
  enabled: false
  name: "queue"
  config: |
    [options]
    server_wide_modules = queue_job,web
    workers = 2
    max_cron_threads = 1
    limit_memory_soft = 3758096384
    limit_memory_hard = 4294967296
    limit_time_cpu = 14400
    limit_time_real = 14400
    limit_time_real_cron = 14400

  replicaCount: 1

  # -- optional extra volumes
  extraVolumes: []

  # -- optional extra volume mounts
  extraVolumeMounts: []

  # -- optional extra containers
  extraContainers: []

  # -- optional extra environment variables
  extraEnv: []
  # - name: DO_STUFF
  #   value: true

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1

upgrade:
  # -- enable click-odoo-update on helm chart upgrade
  enabled: true
  name: "upgrade"

  scale:
    # -- automatically scale down/up the existing deployments before/after upgrade
    enabled: false

    serviceAccount:
      # -- if not set and create is true, upgrade.name is used
      name: ""
      # -- automatically create the service account
      create: true
      # -- service account annotations
      annotations: {}

    image:
      # -- container image
      repository: bitnami/kubectl
      # -- container tag
      tag: "latest"
      # -- container pullPolicy
      pullPolicy: Always

    webCount: 0
    queueCount: 0
    longpollingCount: 0

  # -- customisable arguments for click-odoo-update
  clickArgs: "--ignore-core-addons"

# -- Use extraManifests (string) to add. This is run through the templating system, and may be useful to create custom additional deployments, statefulsets, etc. that need a "rollme" annotation changed to force redeployment after changes are made.
extraManifests: ""

velero:
  # -- enable creation of velero schedule
  enabled: false
  # --- backup schedules must exist in the velero namespace, or Velero will not detect the schedule
  veleroNamespace: "velero"
  # -- the schedule will be named `namespace-of-deployment-chart-name-name`
  name: "backup"
  # -- see https://velero.io/docs/v1.9/customize-installation/#default-pod-volume-backup-to-restic
  defaultVolumesToRestic: true
  # -- see https://velero.io/docs/v1.9/resource-filtering/#--include-cluster-resources
  includeClusterResources: false
  # -- schedule to run on
  schedule: "5 6,12,18 * * *"
  # -- backup retention period
  ttl: 336h0m00s
  # -- automatically take a pg_dump (custom format) of $PGDATABASE to /var/lib/odoo/$PGDATABASE.dump
  pgDumpHook: true
  # -- additional hooks
  extraHooks: []
