apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odoo.config.fullname" . }}
  labels:
    {{- include "odoo.common.labels" . | nindent 4 }}
data:
  PGHOST: {{ .Values.config.postgresql.host | quote }}
  PGPORT: {{ .Values.config.postgresql.port | quote }}
  {{- if not (and .Values.config.postgresql.secretRef .Values.config.postgresql.secretRef.name .Values.config.postgresql.secretRef.keys (hasKey .Values.config.postgresql.secretRef.keys "user")) }}
  PGUSER: {{ .Values.config.postgresql.user | quote }}
  {{- end }}
  PGDATABASE: {{ .Values.config.postgresql.database | quote }}
  PROXY_MODE: {{ .Values.config.proxyMode | quote }}
  WITHOUT_DEMO: {{ .Values.config.withoutDemo | quote }}
  SMTP_SERVER: {{ .Values.config.smtp.host | quote }}
  SMTP_PORT: {{ .Values.config.smtp.port | quote }}
  {{- if not (and .Values.config.smtp.secretRef .Values.config.smtp.secretRef.name .Values.config.smtp.secretRef.keys (hasKey .Values.config.smtp.secretRef.keys "user")) }}
  SMTP_USER: {{ .Values.config.smtp.user | quote }}
  {{- end }}
  SMTP_SSL: {{ .Values.config.smtp.ssl | quote }}
  LIST_DB: {{ .Values.config.listDB | quote }}
  {{- if .Values.config.dbFilter }}
  DB_FILTER: {{ .Values.config.dbFilter | quote }}
  {{- else }}
  DB_FILTER: "^{{ .Values.config.PGDATABASE }}$"
  {{- end }}

  {{- if .Values.web.enabled }}
  web.conf: {{- toYaml .Values.web.config | nindent 4 }}
  {{- end }}

  {{- if .Values.queue.enabled }}
  queue.conf: {{- toYaml .Values.queue.config | nindent 4 }}
  {{- end }}

  {{- if .Values.longpolling.enabled }}
  longpolling.conf: {{- toYaml .Values.longpolling.config | nindent 4 }}
  {{- end }}
