{{- $setPgPassword := not (and .Values.config.postgresql.secretRef .Values.config.postgresql.secretRef.name .Values.config.postgresql.secretRef.keys (hasKey .Values.config.postgresql.secretRef.keys "password")) }}
{{- $setAdminPassword := not (and .Values.config.secretRef .Values.config.secretRef.name .Values.config.secretRef.keys (hasKey .Values.config.secretRef.keys "adminPassword")) }}
{{- $setSmtpPassword := not (and .Values.config.smtp.secretRef .Values.config.smtp.secretRef.name .Values.config.smtp.secretRef.keys (hasKey .Values.config.smtp.secretRef.keys "password")) }}
{{- if or $setPgPassword $setAdminPassword $setSmtpPassword }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "odoo.secret.fullname" . }}
  labels:
    {{- include "odoo.common.labels" . | nindent 4 }}
data:
  {{- if $setPgPassword }}
  PGPASSWORD: {{ .Values.config.postgresql.password | b64enc | quote }}
  {{- end }}
  {{- if $setAdminPassword }}
  ADMIN_PASSWORD: {{ .Values.config.adminPassword | b64enc | quote }}
  {{- end }}
  {{- if $setSmtpPassword }}
  SMTP_PASSWORD: {{ .Values.config.smtp.password | b64enc | quote }}
  {{- end }}
{{- end }}
