{{ if and .Values.velero .Values.velero.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ template "odoo.velero.fullname" . }}
  labels:
    {{- include "odoo.common.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.velero.schedule | quote }}
  template:
    defaultVolumesToRestic: {{ .Values.velero.defaultVolumesToRestic }}
    includeClusterResources: {{ .Values.velero.includeClusterResources }}
    includedNamespaces:
      - {{ .Release.Namespace }}
    ttl: {{ .Values.velero.ttl | quote }}
    {{- if .Values.velero.extraTemplate }}
    {{ .Values.velero.extraTemplate | nindent 4 }}
    {{- end }}
  hooks:
    - name: pgdump
      labelSelector:
        matchLabels:
          {{- include "odoo.web.selectorLabels" . | nindent 10 }}
      pre:
        - exec:
          timeout: 720s
          command:
            - "/bin/bash"
            - "-c"
            - "/usr/bin/pg_dump $PGDATABASE -Fc -f /var/lib/odoo/$PGDATABASE.dump"
      post:
        - exec:
          timeout: 720s
          command:
            - "/bin/bash"
            - "-c"
            - "rm /var/lib/odoo/$PGDATABASE.dump"
{{ end }}
