{{- if and .Values.web.enabled .Values.web.certificate.enabled }}
{{- $fullname := include "odoo.web.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullname }}
spec:
  secretName: {{ $fullname }}
  dnsNames:
    {{- toYaml .Values.web.certificate.dnsNames | nindent 4 }}
  issuerRef:
    {{- toYaml .Values.web.certificate.issuerRef | nindent 4 }}
{{- end }}
