apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "odoo.secret.fullname" . }}
  labels:
    {{- include "odoo.common.labels" . | nindent 4 }}
data:
  PGPASSWORD: {{ .Values.config.postgresql.password | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.config.adminPassword | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.config.smtp.password | b64enc | quote }}
