{{- if .Values.queue.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.queue.fullname" . }}
  labels:
    {{- include "odoo.queue.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.queue.replicaCount }}
  selector:
    matchLabels:
      {{- include "odoo.queue.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        {{- with .Values.queue.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.rollme }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "odoo.queue.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.queue.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.queue.name }}
          securityContext:
            {{- toYaml .Values.queue.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            {{- if .Values.queue.extraEnv }}
              {{- toYaml .Values.queue.extraEnv | nindent 12 }}
            {{- end }}
            {{- include "odoo.common.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.queue.resources | nindent 12 }}
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
            - name: odoo-config
              mountPath: "/opt/odoo/custom/conf.d/"
            {{- if .Values.queue.extraVolumeMounts }}
            {{- toYaml .Values.queue.extraVolumeMounts | nindent 12 }}
            {{- end }}
        {{- if .Values.queue.extraContainers }}
        {{- toYaml .Values.queue.extraContainers | nindent 8 }}
        {{- end }}
      {{- with .Values.queue.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: odoo-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "odoo.persistence.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: odoo-config
          configMap:
            name: {{ include "odoo.config.fullname" . }}
            items:
              - key: "queue.conf"
                path: "99-queue.conf"
        {{- if .Values.queue.extraVolumes }}
        {{- toYaml .Values.queue.extraVolumes | nindent 8 }}
        {{- end }}
{{- end }}
